POST http://localhost:5000/api/users/
Content-Type: application/json
Authorization: Bearer 
{
    "username": "testi2nasasdddasdaasdassadasd1asddasdasdasda2213g@g2oogle.com",
    "name": "Mystery Tester",
    "password": "passwordasdasdd",
    "admin": true
}