POST http://localhost:5000/api/notes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2VAZXhhbXBsZS5jb20iLCJpZCI6MSwiaWF0IjoxNjc5NDY2MzYxfQ.TBukE9lx556nWobF8SK-kNGlQK_rxFKA1rhOdcKBpfo

{
    "author": "testing@google.com",
    "title": "Mystery Tester",
    "content": "1234"
}